#!/bin/bash -e

scriptsDir="./scripts"
. $scriptsDir/common

git log --pretty=format:"%h - %an, %aD : %s" -n 10

update DarkDimius scala scala-scala dotty-library
sbt $sbtArgs update compile "partest-only --show-diff --verbose"

